### ISSUE TITLE
Missing global 'text_visible_poi_landuse_green'

### ISSUE THREAD

**Issue by matteblair** [tangrams/outdoor-style#113]
This global is referenced here:
 - https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L5288
 - https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L5310
 - https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L5334
 - https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L5348
 - https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L5361
 - https://github.com/tangrams/walkabout-style/blob/gh-pages/walkabout-style.yaml#L5373

**Comment by nvkelso** [comment]
Good find! Fixed in 903e714581ecc8b017719af7f39bafd7f62805ed.
