### ISSUE TITLE
bike map - Arguello Blvd colors are funky

### ISSUE THREAD

**Issue by sensescape** [tangrams/outdoor-style#119]
Is this from a filter or global setting?

<img width="674" alt="screen shot 2017-02-06 at 5 19 50 pm" src="https://cloud.githubusercontent.com/assets/466585/22673714/a86e1d52-ec90-11e6-9d50-44ebe0c071d8.png">
http://localhost:8000/#18/37.79355/-122.46064

**Comment by nvkelso** [comment]
Expecting to see blue casing on Arguello Blvd (instead of green) matching
lane no Washington Blvd.

**Comment by sensescape** [comment]
This is fixed now.
