### ISSUE TITLE
[bike map] add bicycle junction "shields"

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#120]
These are common in Europe.

- [x] Functionally complete
- [x] Design polish

**Comment by sensescape** [comment]
- Play with color, desaturated blue or greeen?
- Offset of text a pixel or two compared to icon

**Comment by sensescape** [comment]
<img width="776" alt="screen shot 2017-02-16 at 4 06 24 pm" src="https://cloud.githubusercontent.com/assets/466585/23047023/ed608ec6-f461-11e6-80fc-7a512c16531e.png">
