### ISSUE TITLE
[bike map] highlight regional and national routes

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#121]
- [x] Functional complete
- [x] Add track network highlight

**Comment by sensescape** [comment]
When yellow highlight is added to blue casing, it looks muddy brown? Hard to avoid :\

**Comment by sensescape** [comment]
<img width="683" alt="screen shot 2017-02-16 at 11 42 13 am" src="https://cloud.githubusercontent.com/assets/466585/23037924/02564412-f43d-11e6-84af-d9521ac2dcb4.png">

done
