### ISSUE TITLE
[bike map] Special icon treatment for bike shops, bike parking, etc

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#126]
Work to be performed in the icons repo, but this tracks using in the style.

- [x] Functional complete (with fake `bike-pois` layer)
- [x] Final spritesheet arrangements
- [x] Final spritesheet AI file commit into icons repo
- [x] Final YAML dance to integrate into `pois` layer
- [x] Run anti-alisas script
- [x] Reset icon visibility to default

**Comment by nvkelso** [comment]
Couple different packaging options here.

**Comment by sensescape** [comment]
Related: 

- #147 Experiment with no-badge bike parking icon

**Comment by sensescape** [comment]
~~Waiting to run anti-alias script until bike parking icon completes.~~ Will track this in #147.
