### ISSUE TITLE
Add one-way arrows

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#127]
Also related to bike map

- [x] Functional
- [x] Polish

**Comment by sensescape** [comment]
Refine size transition between first appearance and zoom 18?

**Comment by sensescape** [comment]
<img width="742" alt="screen shot 2017-02-16 at 2 29 44 pm" src="https://cloud.githubusercontent.com/assets/466585/23044297/6f8a0a48-f454-11e6-9065-914055bbd4b0.png">
