### ISSUE TITLE
[bike map] Labels treatment for bike lanes, routes, paths

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#129]
- [x] Typography
- [x] Naming go bold
- [x] Naming removed the left and right parts
- [x] SKIP: Localization (just raw OSM tags now)
- [x] Darken the labels
- [x]  Add labels for `" (walk your bike)"`

**Comment by nvkelso** [comment]
After #130 lands we can remove some of the (left), (right), etc text in these labels.

**Comment by sensescape** [comment]
<img width="785" alt="screen shot 2017-02-16 at 2 15 56 pm" src="https://cloud.githubusercontent.com/assets/466585/23043802/77cf33b0-f452-11e6-9032-b4acc31e1ebc.png">
