### ISSUE TITLE
[bike map] Add new SDK bike route line

### ISSUE THREAD

**Issue by sensescape** [tangrams/outdoor-style#137]
Like we did for transit, but an underlay (like highlight).

@burritojustice can you send us GeoJSON for this? Thanks!

**Comment by nvkelso** [comment]
Added GeoJSON bike route for testing in https://github.com/tangrams/walkabout-style/commit/2350a809a1e97b93d0e63361f52b9049b0d96087. Over to @sensescape for styling :)

**Comment by sensescape** [comment]
This is almost done. Last thing to do here is to set bike layers to visible starting at z16.
<img width="1015" alt="screen shot 2017-02-23 at 3 34 32 pm" src="https://cloud.githubusercontent.com/assets/466585/23283987/cd482d84-f9dd-11e6-8f69-6b0c35a0ee05.png">
<img width="1084" alt="screen shot 2017-02-23 at 3 34 17 pm" src="https://cloud.githubusercontent.com/assets/466585/23283985/cd464514-f9dd-11e6-99b1-3d8d5d90be24.png">
<img width="1016" alt="screen shot 2017-02-23 at 3 33 43 pm" src="https://cloud.githubusercontent.com/assets/466585/23283986/cd4731e0-f9dd-11e6-8d3b-b23245ab0e30.png">
<img width="958" alt="screen shot 2017-02-23 at 3 33 33 pm" src="https://cloud.githubusercontent.com/assets/466585/23283984/cd435494-f9dd-11e6-9ceb-77018aa17f1c.png">

**Comment by sensescape** [comment]
this is all set up:
https://github.com/tangrams/walkabout-style/commit/e04f08eafb0d20567fe6ee59d0aefcc18b0ba9d7
