### ISSUE TITLE
[bike map] oneway arrow should be flat

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#138]
From @tallytalwar comment in https://github.com/tangrams/walkabout-style/pull/115#pullrequestreview-22394284:

While this doesn't matter so much in Tangram JS, in Tangram ES where the view can be pitched to oblique we need the arrow to stay "flat" on the ground plane with the scew'd road.

```
+  filter: { oneway: yes, shield_text: false, $zoom: { min: 17 } }
+            draw:
+                oneway:
+                    sprite: arrow

can we set another property here: flat: true? Refer: https://mapzen.com/documentation/tangram/draw/#flat

P.S. We will need to have this set everywhere we use something like an arrow.
``

**Comment by sensescape** [comment]
https://github.com/tangrams/walkabout-style/commit/83e76751bd1a9e71c0ee34c943a8170003fc3662

this is done, thanks!
