### ISSUE TITLE
Yellow network funk at mid-zooms

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#139]
The yellow network dominates when the road it's intending to highlight doesn't show up. 

If the road isn't visible, then the highlight shouldn't be visible, either? Looks like a problem with `kind_detail`: `secondary` roads.

10/37.9177/-122.3863

<img width="923" alt="screen shot 2017-02-23 at 13 45 08" src="https://cloud.githubusercontent.com/assets/853051/23281202/3988c83a-f9d1-11e6-8e56-ae1fa234efd6.png">

**Comment by sensescape** [comment]
Fixed, added ref=true for secondary road network highlights

<img width="885" alt="screen shot 2017-02-23 at 5 20 29 pm" src="https://cloud.githubusercontent.com/assets/466585/23286511/e286bbac-f9ec-11e6-85ee-2a29110e08a8.png">

https://github.com/tangrams/walkabout-style/commit/93a394cfb38efe9091d3789e026742c8cdc5a711

**Comment by nvkelso** [comment]
I think this is removing highlight from any secondary road that doesn't have a ref value (isn't part of a national or state signed road network)?

Instead of the `ref: true` filter, can you set the highlight line width to 0 "before" zoom 11 (and keep existing zoom 11+ widths?

`width: [[11, 0px], [11, 7px], [12, 10px], [13, 12px], [15, 15px], [17, 24px], [19, 60px], [20, 96px]]`

**Comment by sensescape** [comment]
ok, this is done

https://github.com/tangrams/walkabout-style/commit/f212c5e89668b129d1589df327de97a5a7126a62
