### ISSUE TITLE
Distinguish track and footway

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#141]
In the Marin Headlands and in SF Lands End we're distinguishing between track and footpath at zoom 13, but at zoom 14+ I can't tell the difference (and I should).

Darken footway a smidge at 12/13?
13/37.8306/-122.4950

<img width="798" alt="screen shot 2017-02-23 at 14 10 45" src="https://cloud.githubusercontent.com/assets/853051/23281466/41fef286-f9d2-11e6-8084-0a754e97e15b.png">

Thin trail, lighten brown at 14+?
Marcelo Trail is `footway`, and Bobcat Trail is `track`
16/37.8567/-122.5192

<img width="708" alt="screen shot 2017-02-23 at 14 12 06" src="https://cloud.githubusercontent.com/assets/853051/23281465/41c6648e-f9d2-11e6-965e-96d3c0bb8da8.png">

**Comment by sensescape** [comment]
<img width="649" alt="screen shot 2017-02-23 at 3 24 26 pm" src="https://cloud.githubusercontent.com/assets/466585/23283676/3b204f14-f9dc-11e6-8560-ef85e657df53.png">
this is done

**Comment by nvkelso** [comment]
Zoom 14+ looks great!

But can you darken zoom 13 lines, please?

**Comment by sensescape** [comment]
ok this is done

<img width="620" alt="screen shot 2017-02-24 at 11 10 52 am" src="https://cloud.githubusercontent.com/assets/466585/23317128/f431ca50-fa81-11e6-8434-3bd3528f8a97.png">

**Comment by nvkelso** [comment]
+1 :)
