### ISSUE TITLE
Motorway missing network highlight

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#143]
Pacific Coast Bikeway highlight is missing along some sections of US 101, looks like network highlight needs to be added for motorways at low zooms?

8/40.537/-123.470

<img width="501" alt="screen shot 2017-02-23 at 14 30 18" src="https://cloud.githubusercontent.com/assets/853051/23282104/afd3f624-f9d4-11e6-8f8c-97a8bef9aca2.png">

**Comment by sensescape** [comment]
<img width="624" alt="screen shot 2017-02-23 at 5 06 05 pm" src="https://cloud.githubusercontent.com/assets/466585/23286120/6b3c32ae-f9ea-11e6-94c2-728e8ea40043.png">

thanks, good catch! 
this is done.
