### ISSUE TITLE
Roads with national cycle network should be visible earlier

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#144]
Around Eureka, California we have road data that includes national cycle networks on roads like tertiary that are included in vector tiles, but we remove the styling. Previously we only had the highlight and that was removed, but by removing the highlight then the route has gaps in it (related: https://github.com/tangrams/walkabout-style/issues/139).

At least for national routes let's try and show them earlier? Maybe by adding a holding line on top of the highlight but below the roads? 

11/40.8821/-124.0762

<img width="495" alt="screen shot 2017-02-24 at 09 33 12" src="https://cloud.githubusercontent.com/assets/853051/23313965/ab568030-fa74-11e6-811b-271186483009.png">

<img width="673" alt="screen shot 2017-02-24 at 09 33 08" src="https://cloud.githubusercontent.com/assets/853051/23313966/ab6d178c-fa74-11e6-9c02-ba884b37efaf.png">

**Comment by sensescape** [comment]
this is done

<img width="495" alt="screen shot 2017-02-24 at 11 56 47 am" src="https://cloud.githubusercontent.com/assets/466585/23318756/8df89e88-fa88-11e6-8b85-bb6de55088c2.png">

**Comment by sensescape** [comment]
https://github.com/tangrams/walkabout-style/commit/ca1677a6f29415a408df2f80fe65618b66276991

**Comment by nvkelso** [comment]
Looks great!
