### ISSUE TITLE
Experiment with no-badge bike parking icon

### ISSUE THREAD

**Issue by sensescape** [tangrams/outdoor-style#147]
- [x] New icon, integrate into YAML
- [x] Run anti-alisas script
- [x] Checkin new AI file to icons repo

**Comment by sensescape** [comment]
<img width="621" alt="screen shot 2017-02-28 at 5 23 17 pm" src="https://cloud.githubusercontent.com/assets/466585/23442357/bff926e4-fddc-11e6-8712-f43e3d18281e.png">

**Comment by nvkelso** [comment]
I dig it :)
