### ISSUE TITLE
Road links need bike colors, too

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#148]
- [x] Functional
- [x] Design polish

18/37.74942/-122.40358

<img width="1027" alt="screen shot 2017-02-28 at 15 51 12" src="https://cloud.githubusercontent.com/assets/853051/23439910/d4b8420e-fdcd-11e6-9bff-d89e86a5ff52.png">

**Comment by nvkelso** [comment]
Partial work towards this in cdb3b11d2cda936a2eac7c2e050df69cd69b8a76.

Additional work needed for widths and outer and inner casings, over to @sensescape.

**Highway link:**
19/40.87225/-124.08225

<img width="874" alt="screen shot 2017-02-28 at 16 08 12" src="https://cloud.githubusercontent.com/assets/853051/23440313/37f9e5fa-fdd0-11e6-9436-8494394763f1.png">

**Major road link:**
19/37.74936/-122.40574

<img width="1019" alt="screen shot 2017-02-28 at 16 09 52" src="https://cloud.githubusercontent.com/assets/853051/23440352/68605c6a-fdd0-11e6-976f-54ae709d2e36.png">

**Comment by sensescape** [comment]
<img width="844" alt="screen shot 2017-02-28 at 6 17 54 pm" src="https://cloud.githubusercontent.com/assets/466585/23443235/48ad80f2-fde2-11e6-818b-5f5c9c0733ef.png">
<img width="999" alt="screen shot 2017-02-28 at 6 15 49 pm" src="https://cloud.githubusercontent.com/assets/466585/23443234/48ad7e04-fde2-11e6-8f90-e9d269efdd9e.png">
