### ISSUE TITLE
Add bike coloring for service roads

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#149]
OMG OMG OMG

15/37.7970/-122.4744

This little bit of road is missing color, but does have data.

<img width="816" alt="screen shot 2017-03-06 at 12 01 39" src="https://cloud.githubusercontent.com/assets/853051/23627425/910b47f8-0265-11e7-8a3b-b8435ab215c6.png">

**Comment by sensescape** [comment]
<img width="642" alt="screen shot 2017-03-06 at 1 28 18 pm" src="https://cloud.githubusercontent.com/assets/466585/23630681/d0ac0ea0-0270-11e7-9f24-c532e11cd3ff.png">

this is done
