### ISSUE TITLE
Collision of some features

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/outdoor-style#161]
@nvkelso what is the layer representing those boxes in the screenshot? I couldn't find the layer in the stylesheet, but I guess they are trees. There can be a lot of those around in Paris area parks which can impact performance with our dynamic collision system on tangram-es.

If they don't need collision it would be best turned off.

![screen shot 2017-03-16 at 3 43 30 pm](https://cloud.githubusercontent.com/assets/7061573/24015655/7ad83458-0a5f-11e7-9d4a-2907aa78d2ba.png)

**Comment by nvkelso** [comment]
Those are `kind:tree` features from the POIs layer. It’s probably fine to
turn collision off for them, I’ll have a look. Thanks for the tip!

**Comment by nvkelso** [comment]
Fixed in cf9c622253adc74ad33faae1316483aaa21d610e.

**Comment by nvkelso** [comment]
Actually looks better this way, too! :)

<img width="802" alt="screen shot 2017-04-27 at 17 26 21" src="https://cloud.githubusercontent.com/assets/853051/25509538/ab43058e-2b6e-11e7-8a86-e94289a87103.png">
