### ISSUE TITLE
Color road label stroke per bike class

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#163]
Here in Chicago zoomed out (say 14/41.8885/-87.6364) it's hard to see the bike roads because of the labels on top use grey strokes breaking up the colored bike lanes. Investigate color coding the labels to the line color of underlying road bike's classification.

So West Grand to orange halo, and W Chicago Ave to blue halo.

<img width="1033" alt="screen shot 2017-04-10 at 13 31 22" src="https://cloud.githubusercontent.com/assets/853051/24881316/48efeab6-1df2-11e7-862d-5ca50e1f3759.png">

**Comment by sensescape** [comment]
this is done

<img width="882" alt="screen shot 2017-04-27 at 1 53 47 pm" src="https://cloud.githubusercontent.com/assets/466585/25503974/fb9bc8cc-2b50-11e7-9034-b47acc2ab1be.png">
