### ISSUE TITLE
Missing v5.0.0 tag in walkabout-style-more-labels repo

### ISSUE THREAD

**Issue by rwrx** [tangrams/outdoor-style#185]
I have just noticed that walkabout-style-more-labels repo is missing v5.0.0 tag :). Anyways, this new version is much better than previous!

**Comment by nvkelso** [comment]
Thanks, I'll fix that.

This will probably be lady version with separate repo - future work will only be done in this repo.

**Comment by nvkelso** [comment]
This is fixed:

- https://github.com/tangrams/walkabout-style-more-labels/releases/tag/v5.0.0
