### ISSUE TITLE
Add additional landuse colors at later zooms

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#19]
- [x] Basic
- [ ] Polish

Right now we only color green "park" like things, but there are many other landuse types (hospitals, university, golf course etc). Add those in at zoom 14, adjust to taste.

**Comment by sensescape** [comment]
Look for # GO GREEN & # GO GREY and etc comments in src code for which to work on.

(We removed the bogus ones, don't worry about them anymore.)

**Comment by nvkelso** [comment]
- [ ] `commons` See Rincon Park by the SF office: 18/37.79111/-122.38962
- [ ] `playground`

**Comment by nvkelso** [comment]
Moving commons and playground to next milestone in https://github.com/tangrams/outdoor-style/issues/50, others looking good.
