### ISSUE TITLE
Low zoom hillshading is sad

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#28]
Zoom 7 is okay:

<img width="1190" alt="screen shot 2016-05-05 at 15 22 43" src="https://cloud.githubusercontent.com/assets/853051/15059089/461cbfd6-12d5-11e6-9f04-9f03041a2f13.png">

But zoom 6 and lower needs more exaggeration / less texture in areas of low relief.

zoom 6
<img width="816" alt="screen shot 2016-05-05 at 15 22 36" src="https://cloud.githubusercontent.com/assets/853051/15059086/461bb35c-12d5-11e6-8d44-d08401d517f3.png">

zoom 5
<img width="845" alt="screen shot 2016-05-05 at 15 22 31" src="https://cloud.githubusercontent.com/assets/853051/15059088/461c442a-12d5-11e6-8f98-beb39ae004a7.png">

zoom 4
<img width="715" alt="screen shot 2016-05-05 at 15 22 26" src="https://cloud.githubusercontent.com/assets/853051/15059087/461bdfc6-12d5-11e6-993b-405dbda2b14d.png">

@peter, any advice?

**Comment by meetar** [comment]
@nvkelso How's the low zoom hillshading feeling today? 💊

**Comment by nvkelso** [comment]
Looking much better! There's still a good bit of texturing in low relief areas at zoom 3 and 4, particularly over **Russia**. What's causing that? The sphere map image itself? If an easy fix let's put in this issue, else fork that work for another issue.

**Comment by meetar** [comment]
Yes, I believe it is the spheremap. Whatever is in the middle of the spheremap will show up in the flat areas of the map:

<img width="247" alt="screen shot 2016-05-17 at 10 53 03 am" src="https://cloud.githubusercontent.com/assets/459970/15326990/f0177ea8-1c1d-11e6-87ba-e9e9b00e1a74.png"><img width="258" alt="screen shot 2016-05-17 at 10 54 00 am" src="https://cloud.githubusercontent.com/assets/459970/15327019/06ad8bb2-1c1e-11e6-98dc-9af17c1b7a0e.png">

So if you want the flat areas to be perfectly blank, the center of the spheremap should be blank too.

**Comment by nvkelso** [comment]
We experimented with the center for the refill + hillshading on the bike map and it's working pretty well. Closing this issue. If there is additional work needed we can open new issue in final sprint.
