### ISSUE TITLE
Distinguish sport pitches and meadows

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#45]
- [x] Basic
- [x] Polished

In Golden Gate Park the meadows would be nice to see with a lighter green tint over the park green.
- http://tangrams.github.io/outdoor-style/#17/37.76896/-122.48783

Also the sport pitcehs in this park, maybe with a hairline green stroke?
- http://tangrams.github.io/outdoor-style/#17/37.92245/-122.04457

**Comment by nvkelso** [comment]
Over to Geraldine to for better color treatment.

**Comment by sensescape** [comment]
Look for # GO GREEN & etc comments in src code.

**Comment by nvkelso** [comment]
LGTM, thanks :)
