### ISSUE TITLE
Please for a no-labels version

### ISSUE THREAD

**Issue by thisisaaronland** [tangrams/outdoor-style#47]
Or just documentation about how/whether/where the with-labels version can be modified by a robot to accomplish the same thing. Like this:

https://github.com/thisisaaronland/mapzen-slippy-map/blob/master/Makefile#L16-L19

See attached. I'm just saying...

![slippy-map-20160524-outdoor-9qc0ngd781b4-9qc933j3rvpv](https://cloud.githubusercontent.com/assets/12658759/15507557/ffd04be6-2180-11e6-88c0-584be37d6cf6.png)

**Comment by nvkelso** [comment]
Good idea. We'll support this officially before release.

**Comment by nvkelso** [comment]
This is supported now (just set all the `labels-global:` anchors to `false`), just needs release config.

Preview:

<img width="1440" alt="screen shot 2016-06-13 at 23 44 51" src="https://cloud.githubusercontent.com/assets/853051/16033477/01139f44-31c1-11e6-98a2-e7e227a73970.png">

<img width="1440" alt="screen shot 2016-06-13 at 23 44 08" src="https://cloud.githubusercontent.com/assets/853051/16033479/0145cf8c-31c1-11e6-9431-0ace42b9eca8.png">

**Comment by nvkelso** [comment]
See: 
- https://github.com/tangrams/walkabout-style
- https://github.com/tangrams/walkabout-style-no-labels
- https://github.com/tangrams/walkabout-style-more-labels

**Comment by thisisaaronland** [comment]
![screen shot 2016-07-07 at 08 11 31](https://cloud.githubusercontent.com/assets/12658759/16658254/8b2240b2-441a-11e6-8e61-c47fa9c59388.png)
![screen shot 2016-07-07 at 08 11 42](https://cloud.githubusercontent.com/assets/12658759/16658249/8b043216-441a-11e6-990d-20023d56aa0a.png)

River labels are still being drawn.
