### ISSUE TITLE
Ski icon hard to see among many peak icons

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#49]
Around Tahoe: 11/39.1767/-120.0672

![screen shot 2016-06-06 at 09 03 22](https://cloud.githubusercontent.com/assets/853051/15829236/b76d9ae2-2bc7-11e6-84d7-f11c8dda5fb9.png)

**Comment by sensescape** [comment]
<img width="497" alt="screen shot 2016-06-13 at 5 03 25 pm" src="https://cloud.githubusercontent.com/assets/466585/16027180/c6da9c84-3188-11e6-9d5e-84e12521d75e.png">

fixed
