### ISSUE TITLE
Polish colors for commons and playground areas

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#50]
- [x] `commons` See Rincon Park by the SF office: 18/37.79111/-122.38962
- [x] `playground`

**Comment by sensescape** [comment]
<img width="609" alt="screen shot 2016-06-13 at 5 24 36 pm" src="https://cloud.githubusercontent.com/assets/466585/16027569/b9f00a6a-318b-11e6-9bce-63f8a3b40297.png">
<img width="477" alt="screen shot 2016-06-13 at 5 25 22 pm" src="https://cloud.githubusercontent.com/assets/466585/16027577/d59b484c-318b-11e6-91d4-148b22c6f65e.png">

done
