### ISSUE TITLE
New forest icon / outdoor store icon

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#56]
Give the current tree icon used for outdoor to "forest" stuff, and make a new icon for outdoor gear.

**Comment by nvkelso** [comment]
Forest icon styling is looking good :)

**Comment by sensescape** [comment]
<img width="470" alt="screen shot 2016-06-14 at 10 40 00 am" src="https://cloud.githubusercontent.com/assets/466585/16053142/60477598-321c-11e6-848f-f2f421b70f93.png">
<img width="351" alt="screen shot 2016-06-14 at 10 39 15 am" src="https://cloud.githubusercontent.com/assets/466585/16053147/652fa9cc-321c-11e6-8556-ae7d3504d001.png">
done.
