### ISSUE TITLE
Create new circle generic icons

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#62]
For use with trees, gates, and dams.
- Black circle, same size as the current generic square (gate, dam)
- White circle, same size as the current generic square (tree)
- White circle plus 50% white background circle (to extent of badge) (tree)

The white circles could be colored live in the scene file "green". At zoom 17 trees would get the white circle, then at 19 a scaled down version of the 3rd icon, and at zoom 20 a full size of that 3rd icon?

For trees and gates, see: Upper Noe Rec Center in SF (19/37.74235/-122.42781).
For dam, see: Tennessee Valley Dam in Marin (15/37.8429/-122.5484).

**Comment by sensescape** [comment]
<img width="760" alt="screen shot 2016-06-15 at 11 42 48 am" src="https://cloud.githubusercontent.com/assets/466585/16093293/2abc0536-32f0-11e6-8fbd-47571006255e.png">
<img width="533" alt="screen shot 2016-06-15 at 11 43 10 am" src="https://cloud.githubusercontent.com/assets/466585/16093294/2abecc12-32f0-11e6-86e4-9b123fa82ebb.png">

yay trees!
