### ISSUE TITLE
Add special SEE icon treatment for special places

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#64]
Right now we've optimized the outdoor style for outdoor recreation (or DO). Let's try adding add a second icon treatment (more like we style hospitals where the badge is grey with a color glyph) for places in the urban landscape we go to visit and take in the sights (or SEE). 
- museum
- attraction star
- zoo
- subways (since they help us start/end the walking journey)

**Comment by sensescape** [comment]
<img width="561" alt="screen shot 2016-06-15 at 5 31 18 pm" src="https://cloud.githubusercontent.com/assets/466585/16101867/01a8e766-331f-11e6-9af3-30b7c3f56ace.png">

**Comment by nvkelso** [comment]
Re-opening as there are more transit icons we should do the same color treatment for.

Here in SF at 15/37.7911/-122.3940:

<img width="565" alt="screen shot 2016-06-16 at 10 22 51" src="https://cloud.githubusercontent.com/assets/853051/16126295/554c8e30-33ac-11e6-8dce-cbe46894ee71.png">

**Comment by sensescape** [comment]
<img width="256" alt="screen shot 2016-06-16 at 10 33 38 am" src="https://cloud.githubusercontent.com/assets/466585/16126624/d6f69bbe-33ad-11e6-906a-9fec59ba64c3.png">
