### ISSUE TITLE
Style does not load in Tangram ES

### ISSUE THREAD

**Issue by hallahan** [tangrams/outdoor-style#87]
Just tried using this style in Tangram ES with no luck. On master, commit https://github.com/tangrams/tangram-es/commit/d423f8a85948f5a2d4b601270977a075571ee0fe

<img width="1164" alt="screenshot 2016-08-29 11 55 36" src="https://cloud.githubusercontent.com/assets/556367/18063371/8a3b4146-6ddf-11e6-979a-e9bf960db879.png">

I get the following warning:

```
DEBUG scene.cpp:50: Scene 'walkabout-style/walkabout-style.yaml' => 'walkabout-style/' : 'walkabout-style.yaml'
DEBUG importer.cpp:89: Process: 'walkabout-style/walkabout-style.yaml'
WARNING sceneLoader.cpp:189: No source defined in the yaml scene configuration.
```

**Comment by tallytalwar** [comment]
I just tried this with remote url of `walkabout-style` and this renders for me on linux:

```
./tangram -f https://raw.githubusercontent.com/tangrams/walkabout-style/gh-pages/walkabout-style.yaml
```

**Comment by hallahan** [comment]
Ah, I didn't realize you can do `-f` args.

I've been just resetting `std::string sceneFile`. It looks like I have to give it an absolute path and then it works. Relative path does not.

``` cpp
std::string sceneFile = "/Users/njh/code/tangram-es/scenes/walkabout-style/walkabout-style.yaml";
```
