### ISSUE TITLE
Import ux_language support from bubble-wrap

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/outdoor-style#88]
_From @tallytalwar on September 14, 2016 15:56_

Required for tizen language preference setting.

_Copied from original issue: tangrams/walkabout-style-more-labels#1_

**Comment by nvkelso** [comment]
Related: https://github.com/tangrams/walkabout-style/issues/90

**Comment by tallytalwar** [comment]
Required for https://github.com/mapzen/tizen-maps-plugin-mapzen/issues/61
