### ISSUE TITLE
Import public transit globals from bubble-wrap

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/outdoor-style#89]
_From @tallytalwar on September 14, 2016 15:57_

Refer: https://github.com/tangrams/bubble-wrap/issues/189

_Copied from original issue: tangrams/walkabout-style-more-labels#2_

**Comment by nvkelso** [comment]
Related: https://github.com/tangrams/walkabout-style/issues/90

**Comment by tallytalwar** [comment]
Required for https://github.com/mapzen/tizen-maps-plugin-mapzen/issues/61

**Comment by nvkelso** [comment]
This was done in https://github.com/tangrams/walkabout-style/commit/7b20b9d49f454d97473756f80dfd9b39d842d419.
