### ISSUE TITLE
Import building extrude global from bubble-wrap, and apt filters for footprint

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/outdoor-style#90]
_From @tallytalwar on September 14, 2016 15:58_

Refer: https://github.com/tangrams/bubble-wrap/pull/198 and https://github.com/tangrams/bubble-wrap/issues/200

_Copied from original issue: tangrams/walkabout-style-more-labels#3_

**Comment by nvkelso** [comment]
Related: https://github.com/tangrams/walkabout-style/issues/93

**Comment by tallytalwar** [comment]
Required for https://github.com/mapzen/tizen-maps-plugin-mapzen/issues/61

**Comment by nvkelso** [comment]
This isn't necessary for Walkabout because the buildings only have a touch of extrusion (where in Bubble Wrap the extrusion often covered neighboring roads).

It may be useful to carry over some of the performance optimizations, so leaving this open for a rainy day.

**Comment by nvkelso** [comment]
This has been completed (it basically only turns `extrude: 100` on or off).
