### ISSUE TITLE
Add standard Mapzen UX/UI/SDK elements

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#93]
For overlays and mobile app search, routing assets.

**Comment by matteblair** [comment]
We need this for the Tizen map plugin as well. I'm happy to work on a PR to add this, I just need @nvkelso 's exported sprite definitions with the UX icons included.

**Comment by nvkelso** [comment]
@sensescape Can take care of this. Most the work is in the spritesheet artwork itself. Will prioritize for this week.

**Comment by nvkelso** [comment]
The PR has most the fixes needed but needs to be coordinated with @sensescape's shield work for updated sprites (huzzah binary assets).

It's a mix of Refill and Bubble Wrap styles and assets. If we do this again, Bubble Wrap is canonical, Refill is lacking several styles (like dashed route lines) and uses a pre-reformation set of naming conventions.
