### ISSUE TITLE
All streams are dotted instead of only intermittent features

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#96]
The filter logic hasn't changed in Walkabout, but the rendering has. Is this an upstream Tangram bug?

@sensescape Can you add some screenshots, please? Marin Headlands was where we noticed this.

**Comment by sensescape** [comment]
<img width="745" alt="screen shot 2016-11-15 at 10 22 38 am" src="https://cloud.githubusercontent.com/assets/466585/20318040/7df907d0-ab1d-11e6-822c-2d9ee5b3b872.png">
<img width="488" alt="screen shot 2016-11-15 at 10 22 45 am" src="https://cloud.githubusercontent.com/assets/466585/20318041/7df9a41a-ab1d-11e6-9c14-1ebb15d56c8e.png">
http://localhost:7002/#15/37.8354/-122.5158

**Comment by nvkelso** [comment]
Kinda a dup of the other issue, fixed in https://github.com/tangrams/walkabout-style/commit/33d17d41046b3887296d12859db65b4156381101.
